name = "LitPro"
uuid = "12345678-1234-1234-1234-1234567890ab"
authors = ["Abhishek Shivakumar <abhishek@example.com>"]
version = "1.0.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1.6"